### ISSUE TITLE
Question about the scale alignment factor.

### ISSUE THREAD

**Issue by Cresynia** [zxcqlf/GasMono#2]
I noticed that you mentioned the scale alignment factor in your paper and I want to know what is it ? How to get its standard deviation on the test set? What does the estimated depth align to? I'm a little confused here. I'm new to this field and I'd be very grateful if you could explain.

**Comment by zxcqlf** [comment]
Hi, if you are new to this field, and you want to make some progress, you need to learn some basic knowledge of this field, like multi-view geometry, monocular SLAM, SfM. and then learn the classical self-supervised monocular depth estimation, like monodepth2, sc-depth, and most recent method, like monoViT.

**Comment by Cresynia** [comment]
Ok，Thanks！
